package com.truckintransit.operator.pojo.bookingnotification

data class Data(
    val coupon: String,
    val created: String,
    val customer_id: String,
    val driver_id: Any,
    val drop2_lat: String,
    val drop2_longg: String,
    val drop3_lat: String,
    val drop3_longg: String,
    val drop_lat: String,
    val drop_loc: String,
    val drop_longg: String,
    val dropoff2: String,
    val dropoff3: String,
    val freightpayment: String,
    val material_type: String,
    val optionshelper: String,
    val payment_mode: String,
    val pickup2: String,
    val pickup2_lat: String,
    val pickup2_longgg: String,
    val pickup3: String,
    val pickup3_lat: String,
    val pickup3_longg: String,
    val pickup_lat: String,
    val pickup_loc: String,
    val pickup_longg: String,
    val serviceid: String,
    val titcredits: String,
    val trip_distance: Any,
    val truckid: String,
    val vehiclebodytype: String,
    val vehiclefueltypeid: String,
    val vehicletypeid: String
)